### ISSUE TITLE
storage upload mp3 file is defaulting to text/plain MIME type

### ISSUE THREAD

**Issue by jeo1kim** [supabase-community/storage-py#144]
**Describe the bug**

**To Reproduce**
        supabase.storage.from_(PUBLIC_BUCKET).upload(f"{filename}", join('/tmp', filename), file_options={"cache-control": "3600", "content_type": "audio/mpeg", "x-upsert": "false"})
        
        I am using nextjs, vercel and python. I am calling the upload function but am getting this error. When I open the bucket to accept all MIME type I can see the file being created but the MIME type is text/plain. 
        
        `supabase.storage.from_(PUBLIC_BUCKET).upload(f"{filename}", join('/tmp', filename), file_options={"content_type": "audio/mpeg"})
File "/var/task/storage3/_sync/file_api.py", line 232, in upload
return self._request(
File "/var/task/storage3/_sync/file_api.py", line 48, in _request
raise StorageException(
storage3.utils.StorageException: {'statusCode': 400, 'error': 'invalid_mime_type', 'message': 'mi`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by J0** [comment]
Hey team,

As @radfaz mentioned you'll probably want to specify the `mime_type` like

```
with open("/content/sample-5s.mp4", 'rb') as f:
  supabase.storage.from_("testbucket").upload(file=f,path="sample.mp4", file_options={"content-type": "audio/mpeg"})
```

Will update the docs to reflect this.

Going to close but please feel free to re-open if there are further issues

**Comment by libratiger** [comment]
why we pop the "content-type" from the header option, so no matter what the user set ,it always use the "text/plain". @J0  @radfaz
