### ISSUE TITLE
Getting !!! TypeError: __init__() got an unexpected keyword argument 'file_size_limit'

### ISSUE THREAD

**Issue by starascendin** [supabase-community/storage-py#71]
**Describe the bug**
Using supabase 1.0.1 and storage3 0.5.0, i'm getting error `!!! TypeError: __init__() got an unexpected keyword argument 'file_size_limit'`

```
        res = self._request("GET", f"/bucket/{id}")
        json = res.json()
        return SyncBucket(**json, _client=self._client)

```

**Comment by conanmalanaphy** [comment]
I'm also getting this error

**Comment by GaryAustin1** [comment]
This is likely do to a change in the storage.buckets table adding new columns for coming features(?)....
![image](https://user-images.githubusercontent.com/54564956/221665132-6ca0c03c-7905-42bb-b710-3a00f1350a6c.png)

**Comment by conanmalanaphy** [comment]
Thanks for that - it's answered the question :D but is there anything I can do to fix this or do we need to wait for a dev?

**Comment by GaryAustin1** [comment]
Seems like python cares about the structure of the buckets table for some reason, but as I mentioned in Discord I don't know anything about python.  Is there away to turn of the "type checking" that is going on?   Otherwise, if you could figure out in this python code what needs to be added to deal with the new columns and generate your own temp version that would be one way.  

I don't think it is wise, or possibly even possible, to delete those columns from storage.buckets until it gets fixed here as that might break the storage-api code.

**Comment by conanmalanaphy** [comment]
How long does it normally take to fix issues. I can assume this one isn't too difficult.

**Comment by ChartierLuc** [comment]
@starascendin 
@conanmalanaphy 

[This PR](https://github.com/supabase-community/storage-py/pull/72) fixes the issue for me.

Uninstall storage3 and install it with pip
```
pip uninstall storage3
pip install git+https://github.com/supabase-community/storage-py.git@refs/pull/72/merge
```

**Comment by starascendin** [comment]
> @starascendin @conanmalanaphy
> 
> [This PR](https://github.com/supabase-community/storage-py/pull/72) fixes the issue for me.
> 
> Uninstall storage3 and install it with pip
> 
> ```
> pip uninstall storage3
> pip install git+https://github.com/supabase-community/storage-py.git@refs/pull/72/merge
> ```

confirm this fixes the issue.

Hope the devs can merge in this fix and update the package

**Comment by J0** [comment]
Hey team, 

Thanks for the quick PR! We'll review by end of day and have a release out by the end of the weekend :)

**Comment by J0** [comment]
published new release, feel free to ping me again if there are issues.

Once again,  thanks @ChartierLuc for the PR!
